./read_and_plot_interpolation BulkG el_HPW WW interpolationFiles/
./read_and_plot_interpolation BulkG mu_HPW WW interpolationFiles/
./read_and_plot_interpolation BulkG el_LPW WW interpolationFiles/
./read_and_plot_interpolation BulkG mu_LPW WW interpolationFiles/
./read_and_plot_interpolation BulkG el_HPZ WW interpolationFiles/
./read_and_plot_interpolation BulkG mu_HPZ WW interpolationFiles/
./read_and_plot_interpolation BulkG el_LPZ WW interpolationFiles/
./read_and_plot_interpolation BulkG mu_LPZ WW interpolationFiles/
./read_and_plot_interpolation Wprime el_HPW WZ interpolationFiles/
./read_and_plot_interpolation Wprime mu_HPW WZ interpolationFiles/
./read_and_plot_interpolation Wprime el_LPW WZ interpolationFiles/
./read_and_plot_interpolation Wprime mu_LPW WZ interpolationFiles/
./read_and_plot_interpolation Wprime el_HPZ WZ interpolationFiles/
./read_and_plot_interpolation Wprime mu_HPZ WZ interpolationFiles/
./read_and_plot_interpolation Wprime el_LPZ WZ interpolationFiles/
./read_and_plot_interpolation Wprime mu_LPZ WZ interpolationFiles/