./interpolate BulkG el_HPW WW /afs/cern.ch/user/l/lbrianza/work/public/13TeV_datacards_Spring15/ /afs/cern.ch/user/l/lbrianza/work/public/logFiles_spring15/
./interpolate BulkG mu_HPW WW /afs/cern.ch/user/l/lbrianza/work/public/13TeV_datacards_Spring15/ /afs/cern.ch/user/l/lbrianza/work/public/logFiles_spring15/
./interpolate BulkG el_LPW WW /afs/cern.ch/user/l/lbrianza/work/public/13TeV_datacards_Spring15/ /afs/cern.ch/user/l/lbrianza/work/public/logFiles_spring15/
./interpolate BulkG mu_LPW WW /afs/cern.ch/user/l/lbrianza/work/public/13TeV_datacards_Spring15/ /afs/cern.ch/user/l/lbrianza/work/public/logFiles_spring15/
./interpolate BulkG el_HPZ WW /afs/cern.ch/user/l/lbrianza/work/public/13TeV_datacards_Spring15/ /afs/cern.ch/user/l/lbrianza/work/public/logFiles_spring15/
./interpolate BulkG mu_HPZ WW /afs/cern.ch/user/l/lbrianza/work/public/13TeV_datacards_Spring15/ /afs/cern.ch/user/l/lbrianza/work/public/logFiles_spring15/
./interpolate BulkG el_LPZ WW /afs/cern.ch/user/l/lbrianza/work/public/13TeV_datacards_Spring15/ /afs/cern.ch/user/l/lbrianza/work/public/logFiles_spring15/
./interpolate BulkG mu_LPZ WW /afs/cern.ch/user/l/lbrianza/work/public/13TeV_datacards_Spring15/ /afs/cern.ch/user/l/lbrianza/work/public/logFiles_spring15/
./interpolate Wprime el_HPW WZ /afs/cern.ch/user/l/lbrianza/work/public/13TeV_datacards_Spring15/ /afs/cern.ch/user/l/lbrianza/work/public/logFiles_spring15/
./interpolate Wprime mu_HPW WZ /afs/cern.ch/user/l/lbrianza/work/public/13TeV_datacards_Spring15/ /afs/cern.ch/user/l/lbrianza/work/public/logFiles_spring15/
./interpolate Wprime el_LPW WZ /afs/cern.ch/user/l/lbrianza/work/public/13TeV_datacards_Spring15/ /afs/cern.ch/user/l/lbrianza/work/public/logFiles_spring15/
./interpolate Wprime mu_LPW WZ /afs/cern.ch/user/l/lbrianza/work/public/13TeV_datacards_Spring15/ /afs/cern.ch/user/l/lbrianza/work/public/logFiles_spring15/
./interpolate Wprime el_HPZ WZ /afs/cern.ch/user/l/lbrianza/work/public/13TeV_datacards_Spring15/ /afs/cern.ch/user/l/lbrianza/work/public/logFiles_spring15/
./interpolate Wprime mu_HPZ WZ /afs/cern.ch/user/l/lbrianza/work/public/13TeV_datacards_Spring15/ /afs/cern.ch/user/l/lbrianza/work/public/logFiles_spring15/
./interpolate Wprime el_LPZ WZ /afs/cern.ch/user/l/lbrianza/work/public/13TeV_datacards_Spring15/ /afs/cern.ch/user/l/lbrianza/work/public/logFiles_spring15/
./interpolate Wprime mu_LPZ WZ /afs/cern.ch/user/l/lbrianza/work/public/13TeV_datacards_Spring15/ /afs/cern.ch/user/l/lbrianza/work/public/logFiles_spring15/